package vars

const ApiOutputDir = "apis"
const ApiTemplateFile = "api.go.tmpl"
const StructOutputDir = "structs"
const StructTemplateFile = "struct.go.tmpl"

var SupportedAPIs = map[string]bool{
	"associateIpAddress":                true,
	"disassociateIpAddress":             true,
	"listPublicIpAddresses":             true,
	"updateIpAddress":                   true,
	"createAffinityGroup":               true,
	"deleteAffinityGroup":               true,
	"listAffinityGroups":                true,
	"updateVMAffinityGroup":             true,
	"listAffinityGroupTypes":            true,
	"createDiskOffering":                true,
	"updateDiskOffering":                true,
	"deleteDiskOffering":                true,
	"listDiskOfferings":                 true,
	"listPortForwardingRules":           true,
	"createPortForwardingRule":          true,
	"deletePortForwardingRule":          true,
	"updatePortForwardingRule":          true,
	"createFirewallRule":                true,
	"deleteFirewallRule":                true,
	"listFirewallRules":                 true,
	"updateFirewallRule":                true,
	"createEgressFirewallRule":          true,
	"deleteEgressFirewallRule":          true,
	"listEgressFirewallRules":           true,
	"updateEgressFirewallRule":          true,
	"enableStaticNat":                   true,
	"createIpForwardingRule":            true,
	"deleteIpForwardingRule":            true,
	"listIpForwardingRules":             true,
	"disableStaticNat":                  true,
	"createNetwork":                     true,
	"deleteNetwork":                     true,
	"listNetworks":                      true,
	"restartNetwork":                    true,
	"updateNetwork":                     true,
	"createNetworkOffering":             true,
	"updateNetworkOffering":             true,
	"deleteNetworkOffering":             true,
	"listNetworkOfferings":              true,
	"createTags":                        true,
	"deleteTags":                        true,
	"listTags":                          true,
	"createSecurityGroup":               true,
	"deleteSecurityGroup":               true,
	"authorizeSecurityGroupIngress":     true,
	"revokeSecurityGroupIngress":        true,
	"authorizeSecurityGroupEgress":      true,
	"revokeSecurityGroupEgress":         true,
	"listSecurityGroups":                true,
	"createServiceOffering":             true,
	"deleteServiceOffering":             true,
	"updateServiceOffering":             true,
	"listServiceOfferings":              true,
	"createTemplate":                    true,
	"registerTemplate":                  true,
	"updateTemplate":                    true,
	"copyTemplate":                      true,
	"deleteTemplate":                    true,
	"listTemplates":                     true,
	"updateTemplatePermissions":         true,
	"listTemplatePermissions":           true,
	"extractTemplate":                   true,
	"prepareTemplate":                   true,
	"deployVirtualMachine":              true,
	"destroyVirtualMachine":             true,
	"rebootVirtualMachine":              true,
	"startVirtualMachine":               true,
	"stopVirtualMachine":                true,
	"resetPasswordForVirtualMachine":    true,
	"updateVirtualMachine":              true,
	"listVirtualMachines":               true,
	"getVMPassword":                     true,
	"restoreVirtualMachine":             true,
	"changeServiceForVirtualMachine":    true,
	"scaleVirtualMachine":               true,
	"assignVirtualMachine":              true,
	"migrateVirtualMachine":             true,
	"migrateVirtualMachineWithVolume":   true,
	"recoverVirtualMachine":             true,
	"expungeVirtualMachine":             true,
	"cleanVMReservations":               true,
	"addNicToVirtualMachine":            true,
	"removeNicFromVirtualMachine":       true,
	"updateDefaultNicForVirtualMachine": true,
	"attachVolume":                      true,
	"uploadVolume":                      true,
	"detachVolume":                      true,
	"createVolume":                      true,
	"deleteVolume":                      true,
	"listVolumes":                       true,
	"extractVolume":                     true,
	"migrateVolume":                     true,
	"resizeVolume":                      true,
	"updateVolume":                      true,
	"createZone":                        true,
	"updateZone":                        true,
	"deleteZone":                        true,
	"listZones":                         true,
}

var FileApiMap = map[string][]string{
	"APIDiscovery": []string{
		"listApis",
	},
	"Account": []string{
		"createAccount",
		"deleteAccount",
		"updateAccount",
		"disableAccount",
		"enableAccount",
		"lockAccount",
		"listAccounts",
		"markDefaultZoneForAccount",
		"addAccountToProject",
		"deleteAccountFromProject",
	},
	"Address": []string{
		"associateIpAddress",
		"disassociateIpAddress",
		"listPublicIpAddresses",
		"updateIpAddress",
	},
	"AffinityGroup": []string{
		"createAffinityGroup",
		"deleteAffinityGroup",
		"listAffinityGroups",
		"updateVMAffinityGroup",
		"listAffinityGroupTypes",
	},
	"Alert": []string{
		"listAlerts",
		"archiveAlerts",
		"deleteAlerts",
		"generateAlert",
	},
	"Asyncjob": []string{
		"queryAsyncJobResult",
		"listAsyncJobs",
	},
	"AutoScale": []string{
		"createCounter",
		"createCondition",
		"createAutoScalePolicy",
		"createAutoScaleVmProfile",
		"createAutoScaleVmGroup",
		"deleteCounter",
		"deleteCondition",
		"deleteAutoScalePolicy",
		"deleteAutoScaleVmProfile",
		"deleteAutoScaleVmGroup",
		"listCounters",
		"listConditions",
		"listAutoScalePolicies",
		"listAutoScaleVmProfiles",
		"listAutoScaleVmGroups",
		"enableAutoScaleVmGroup",
		"disableAutoScaleVmGroup",
		"updateAutoScalePolicy",
		"updateAutoScaleVmProfile",
		"updateAutoScaleVmGroup",
	},
	"Baremetal": []string{
		"addBaremetalPxeKickStartServer",
		"addBaremetalPxePingServer",
		"addBaremetalDhcp",
		"listBaremetalDhcp",
		"listBaremetalPxeServers",
	},
	"BigSwitchVNS": []string{
		"addBigSwitchVnsDevice",
		"deleteBigSwitchVnsDevice",
		"listBigSwitchVnsDevices",
	},
	"Certificate": []string{
		"uploadCustomCertificate",
	},
	"CloudIdentifier": []string{
		"getCloudIdentifier",
	},
	"Cluster": []string{
		"addCluster",
		"deleteCluster",
		"updateCluster",
		"listClusters",
		"dedicateCluster",
		"releaseDedicatedCluster",
		"listDedicatedClusters",
	},
	"Configuration": []string{
		"updateConfiguration",
		"listConfigurations",
		"listCapabilities",
		"listDeploymentPlanners",
		"listLdapConfigurations",
		"addLdapConfiguration",
		"deleteLdapConfiguration",
	},
	"DiskOffering": []string{
		"createDiskOffering",
		"updateDiskOffering",
		"deleteDiskOffering",
		"listDiskOfferings",
	},
	"Domain": []string{
		"createDomain",
		"updateDomain",
		"deleteDomain",
		"listDomains",
		"listDomainChildren",
	},
	"Event": []string{
		"listEvents",
		"listEventTypes",
		"archiveEvents",
		"deleteEvents",
	},
	"Firewall": []string{
		"listPortForwardingRules",
		"createPortForwardingRule",
		"deletePortForwardingRule",
		"updatePortForwardingRule",
		"createFirewallRule",
		"deleteFirewallRule",
		"listFirewallRules",
		"updateFirewallRule",
		"createEgressFirewallRule",
		"deleteEgressFirewallRule",
		"listEgressFirewallRules",
		"updateEgressFirewallRule",
		// "addPaloAltoFirewall",
		// "deletePaloAltoFirewall",
		// "configurePaloAltoFirewall",
		// "listPaloAltoFirewalls",
	},
	"GuestOS": []string{
		"listOsTypes",
		"listOsCategories",
		"addGuestOs",
		"updateGuestOs",
		"removeGuestOs",
		"listGuestOsMapping",
		"addGuestOsMapping",
		"updateGuestOsMapping",
		"removeGuestOsMapping",
	},
	"Host": []string{
		"addHost",
		"reconnectHost",
		"updateHost",
		"deleteHost",
		"prepareHostForMaintenance",
		"cancelHostMaintenance",
		"listHosts",
		"listHostTags",
		"findHostsForMigration",
		"updateHostPassword",
		"releaseHostReservation",
		"addBaremetalHost",
		"dedicateHost",
		"releaseDedicatedHost",
		"listDedicatedHosts",
	},
	"Hypervisor": []string{
		"listHypervisors",
		"updateHypervisorCapabilities",
		"listHypervisorCapabilities",
	},
	"ISO": []string{
		"attachIso",
		"detachIso",
		"listIsos",
		"registerIso",
		"updateIso",
		"deleteIso",
		"copyIso",
		"updateIsoPermissions",
		"listIsoPermissions",
		"extractIso",
	},
	"ImageStore": []string{
		"addImageStore",
		"addSecondaryStorage",
		"listImageStores",
		"deleteImageStore",
		"createSecondaryStagingStore",
		"listSecondaryStagingStores",
		"deleteSecondaryStagingStore",
		"updateCloudToUseObjectStore",
	},
	"InternalLB": []string{
		"configureInternalLoadBalancerElement",
		"createInternalLoadBalancerElement",
		"listInternalLoadBalancerElements",
		"stopInternalLoadBalancerVM",
		"startInternalLoadBalancerVM",
		"listInternalLoadBalancerVMs",
	},
	"LDAP": []string{
		"ldapCreateAccount",
	},
	"Limit": []string{
		"updateResourceLimit",
		"updateResourceCount",
		"listResourceLimits",
		"getApiLimit",
		"resetApiLimit",
	},
	"LoadBalancer": []string{
		"createLoadBalancerRule",
		"deleteLoadBalancerRule",
		"removeFromLoadBalancerRule",
		"assignToLoadBalancerRule",
		// "createLBStickinessPolicy",
		// "updateLBStickinessPolicy",
		// "deleteLBStickinessPolicy",
		"listLoadBalancerRules",
		// "listLBStickinessPolicies",
		// "listLBHealthCheckPolicies",
		// "createLBHealthCheckPolicy",
		// "updateLBHealthCheckPolicy",
		// "deleteLBHealthCheckPolicy",
		"listLoadBalancerRuleInstances",
		"updateLoadBalancerRule",
		// "uploadSslCert",
		// "deleteSslCert",
		// "listSslCerts",
		// "assignCertToLoadBalancer",
		// "removeCertFromLoadBalancer",
		// "addNetscalerLoadBalancer",
		// "deleteNetscalerLoadBalancer",
		// "configureNetscalerLoadBalancer",
		// "listNetscalerLoadBalancers",
		// "createGlobalLoadBalancerRule",
		// "deleteGlobalLoadBalancerRule",
		// "updateGlobalLoadBalancerRule",
		// "listGlobalLoadBalancerRules",
		// "assignToGlobalLoadBalancerRule",
		// "removeFromGlobalLoadBalancerRule",
		// "createLoadBalancer",
		// "listLoadBalancers",
		// "deleteLoadBalancer",
		// "updateLoadBalancer",
	},
	"NAT": []string{
		"enableStaticNat",
		"createIpForwardingRule",
		"deleteIpForwardingRule",
		"listIpForwardingRules",
		"disableStaticNat",
	},
	"Network": []string{
		// "dedicatePublicIpRange",
		// "releasePublicIpRange",
		"createNetwork",
		"deleteNetwork",
		"listNetworks",
		"restartNetwork",
		"updateNetwork",
		// "createPhysicalNetwork",
		// "deletePhysicalNetwork",
		// "listPhysicalNetworks",
		/* "updatePhysicalNetwork", */
		// "listSupportedNetworkServices",
		// "addNetworkServiceProvider",
		// "deleteNetworkServiceProvider",
		// "listNetworkServiceProviders",
		// "updateNetworkServiceProvider",
		// "createStorageNetworkIpRange",
		// "deleteStorageNetworkIpRange",
		// "listStorageNetworkIpRange",
		// "updateStorageNetworkIpRange",
		// "listPaloAltoFirewallNetworks",
		// "listNetscalerLoadBalancerNetworks",
		// "listNiciraNvpDeviceNetworks",
		// "listNetworkIsolationMethods",
	},
	"NetworkACL": []string{
		"createNetworkACL",
		"updateNetworkACLItem",
		"deleteNetworkACL",
		"listNetworkACLs",
		"createNetworkACLList",
		"deleteNetworkACLList",
		"replaceNetworkACLList",
		"listNetworkACLLists",
		"updateNetworkACLList",
	},
	"NetworkDevice": []string{
		"addNetworkDevice",
		"listNetworkDevice",
		"deleteNetworkDevice",
	},
	"NetworkOffering": []string{
		"createNetworkOffering",
		"updateNetworkOffering",
		"deleteNetworkOffering",
		"listNetworkOfferings",
	},
	"Nic": []string{
		"addIpToNic",
		"removeIpFromNic",
		"listNics",
	},
	"NiciraNVP": []string{
		"addNiciraNvpDevice",
		"deleteNiciraNvpDevice",
		"listNiciraNvpDevices",
	},
	"OvsElement": []string{
		"configureOvsElement",
		"listOvsElements",
	},
	"Pod": []string{
		"createPod",
		"updatePod",
		"deletePod",
		"listPods",
		"dedicatePod",
		"releaseDedicatedPod",
		"listDedicatedPods",
	},
	"PortableIP": []string{
		"createPortableIpRange",
		"deletePortableIpRange",
		"listPortableIpRanges",
	},
	"Project": []string{
		"createProject",
		"deleteProject",
		"updateProject",
		"activateProject",
		"suspendProject",
		"listProjects",
		"listProjectAccounts",
		"listProjectInvitations",
		"updateProjectInvitation",
		"deleteProjectInvitation",
	},
	"Region": []string{
		"addRegion",
		"updateRegion",
		"removeRegion",
		"listRegions",
	},
	"Resourcemetadata": []string{
		"addResourceDetail",
		"removeResourceDetail",
		"listResourceDetails",
	},
	"Resourcetags": []string{
		"createTags",
		"deleteTags",
		"listTags",
		"listStorageTags",
	},
	"Router": []string{
		"startRouter",
		"rebootRouter",
		"stopRouter",
		"destroyRouter",
		"changeServiceForRouter",
		"listRouters",
		"listVirtualRouterElements",
		"configureVirtualRouterElement",
		"createVirtualRouterElement",
	},
	"S3": []string{
		"addS3",
		"listS3s",
	},
	"SSH": []string{
		"resetSSHKeyForVirtualMachine",
		"registerSSHKeyPair",
		"createSSHKeyPair",
		"deleteSSHKeyPair",
		"listSSHKeyPairs",
	},
	"SecurityGroup": []string{
		"createSecurityGroup",
		"deleteSecurityGroup",
		"authorizeSecurityGroupIngress",
		"revokeSecurityGroupIngress",
		"authorizeSecurityGroupEgress",
		"revokeSecurityGroupEgress",
		"listSecurityGroups",
	},
	"ServiceOffering": []string{
		"createServiceOffering",
		"deleteServiceOffering",
		"updateServiceOffering",
		"listServiceOfferings",
	},
	"Snapshot": []string{
		"createSnapshot",
		"listSnapshots",
		"deleteSnapshot",
		"createSnapshotPolicy",
		"updateSnapshotPolicy",
		"deleteSnapshotPolicies",
		"listSnapshotPolicies",
		"revertSnapshot",
		"listVMSnapshot",
		"createVMSnapshot",
		"deleteVMSnapshot",
		"revertToVMSnapshot",
	},
	"StoragePool": []string{
		"listStoragePools",
		"createStoragePool",
		"updateStoragePool",
		"deleteStoragePool",
		"findStoragePoolsForMigration",
		"enableStorageMaintenance",
		"cancelStorageMaintenance",
	},
	"StorageProvider": []string{
		"listStorageProviders",
	},
	"StratosphereSSP": []string{
		"addStratosphereSsp",
	},
	"Swift": []string{
		"addSwift",
		"listSwifts",
	},
	"SystemCapacity": []string{
		"listCapacity",
	},
	"SystemVM": []string{
		"startSystemVm",
		"rebootSystemVm",
		"stopSystemVm",
		"destroySystemVm",
		"listSystemVms",
		"migrateSystemVm",
		"changeServiceForSystemVm",
		"scaleSystemVm",
	},
	"Template": []string{
		"createTemplate",
		"registerTemplate",
		"updateTemplate",
		"copyTemplate",
		"deleteTemplate",
		"listTemplates",
		"updateTemplatePermissions",
		"listTemplatePermissions",
		"extractTemplate",
		"prepareTemplate",
		// "upgradeRouterTemplate",
	},
	"UCS": []string{
		"addUcsManager",
		"listUcsManagers",
		"listUcsProfiles",
		"listUcsBlades",
		"associateUcsProfileToBlade",
	},
	"Usage": []string{
		"addTrafficType",
		"deleteTrafficType",
		"listTrafficTypes",
		"updateTrafficType",
		"listTrafficTypeImplementors",
		"generateUsageRecords",
		"listUsageRecords",
		"listUsageTypes",
		"addTrafficMonitor",
		"deleteTrafficMonitor",
		"listTrafficMonitors",
	},
	"User": []string{
		"createUser",
		"deleteUser",
		"updateUser",
		"listUsers",
		"lockUser",
		"disableUser",
		"enableUser",
		"getUser",
		"registerUserKeys",
		"listLdapUsers",
		"importLdapUsers",
	},
	"VLAN": []string{
		"createVlanIpRange",
		"deleteVlanIpRange",
		"listVlanIpRanges",
		"dedicateGuestVlanRange",
		"releaseDedicatedGuestVlanRange",
		"listDedicatedGuestVlanRanges",
	},
	"VMGroup": []string{
		"createInstanceGroup",
		"deleteInstanceGroup",
		"updateInstanceGroup",
		"listInstanceGroups",
	},
	"VPC": []string{
		"createVPC",
		"listVPCs",
		"deleteVPC",
		"updateVPC",
		"restartVPC",
		"createVPCOffering",
		"updateVPCOffering",
		"deleteVPCOffering",
		"listVPCOfferings",
		"createPrivateGateway",
		"listPrivateGateways",
		"deletePrivateGateway",
		"createStaticRoute",
		"deleteStaticRoute",
		"listStaticRoutes",
	},
	"VPN": []string{
		"createRemoteAccessVpn",
		"deleteRemoteAccessVpn",
		"listRemoteAccessVpns",
		"updateRemoteAccessVpn",
		"addVpnUser",
		"removeVpnUser",
		"listVpnUsers",
		"createVpnCustomerGateway",
		"createVpnGateway",
		"createVpnConnection",
		"deleteVpnCustomerGateway",
		"deleteVpnGateway",
		"deleteVpnConnection",
		"updateVpnCustomerGateway",
		"resetVpnConnection",
		"listVpnCustomerGateways",
		"listVpnGateways",
		"listVpnConnections",
		"updateVpnConnection",
		"updateVpnGateway",
	},
	"VirtualMachine": []string{
		"deployVirtualMachine",
		"destroyVirtualMachine",
		"rebootVirtualMachine",
		"startVirtualMachine",
		"stopVirtualMachine",
		"resetPasswordForVirtualMachine",
		"updateVirtualMachine",
		"listVirtualMachines",
		"getVMPassword",
		"getVirtualMachineUserData",
		"restoreVirtualMachine",
		"changeServiceForVirtualMachine",
		"scaleVirtualMachine",
		"assignVirtualMachine",
		"migrateVirtualMachine",
		"migrateVirtualMachineWithVolume",
		"recoverVirtualMachine",
		"expungeVirtualMachine",
		"cleanVMReservations",
		"addNicToVirtualMachine",
		"removeNicFromVirtualMachine",
		"updateDefaultNicForVirtualMachine",
	},
	"Volume": []string{
		"attachVolume",
		"uploadVolume",
		"detachVolume",
		"createVolume",
		"deleteVolume",
		"listVolumes",
		"extractVolume",
		"migrateVolume",
		"resizeVolume",
		"updateVolume",
	},
	"Zone": []string{
		"createZone",
		"updateZone",
		"deleteZone",
		"listZones",
		// "dedicateZone",
		// "releaseDedicatedZone",
		// "listDedicatedZones",
	},
}

var ApiToObjectNameMap = map[string]string{
	"activateProject":                             "project",
	"addAccountToProject":                         "result",
	"addBaremetalDhcp":                            "baremetaldhcp",
	"addBaremetalHost":                            "host",
	"addBaremetalPxeKickStartServer":              "baremetalpxekickstartserver",
	"addBaremetalPxePingServer":                   "baremetalpxepingserver",
	"addCiscoAsa1000vResource":                    "ciscoasa1000vresource",
	"addCiscoVnmcResource":                        "ciscovnmcresource",
	"addCluster":                                  "cluster",
	"addExternalFirewall":                         "externalfirewall",
	"addExternalLoadBalancer":                     "externalloadbalancer",
	"addF5LoadBalancer":                           "f5loadbalancer",
	"addHost":                                     "host",
	"addImageStore":                               "imagestore",
	"addIpToNic":                                  "iptonic",
	"addNetscalerLoadBalancer":                    "netscalerloadbalancer",
	"addNetworkDevice":                            "networkdevice",
	"addNetworkServiceProvider":                   "networkserviceprovider",
	"addNicToVirtualMachine":                      "virtualmachine",
	"addNiciraNvpDevice":                          "niciranvpdevice",
	"addRegion":                                   "region",
	"addResourceDetail":                           "result",
	"addS3":                                       "s3",
	"addSecondaryStorage":                         "imagestore",
	"addSrxFirewall":                              "srxfirewall",
	"addSwift":                                    "swift",
	"addTrafficMonitor":                           "trafficmonitor",
	"addTrafficType":                              "traffictype",
	"addUcsManager":                               "ucsmanager",
	"addVmwareDc":                                 "vmwaredc",
	"addVpnUser":                                  "vpnuser",
	"archiveAlerts":                               "result",
	"archiveEvents":                               "result",
	"assignToGlobalLoadBalancerRule":              "result",
	"assignToLoadBalancerRule":                    "result",
	"assignVirtualMachine":                        "virtualmachine",
	"associateIpAddress":                          "publicipaddress",
	"associateLun":                                "lun",
	"associateUcsProfileToBlade":                  "ucsprofiletoblade",
	"attachIso":                                   "virtualmachine",
	"attachVolume":                                "volume",
	"authorizeSecurityGroupEgress":                "securitygroupegress",
	"authorizeSecurityGroupIngress":               "securitygroupingress",
	"cancelHostMaintenance":                       "host",
	"cancelStorageMaintenance":                    "storagepool",
	"changeServiceForRouter":                      "router",
	"changeServiceForSystemVm":                    "systemvm",
	"changeServiceForVirtualMachine":              "virtualmachine",
	"cleanVMReservations":                         "result",
	"configureF5LoadBalancer":                     "f5loadbalancer",
	"configureInternalLoadBalancerElement":        "internalloadbalancerelement",
	"configureNetscalerLoadBalancer":              "netscalerloadbalancer",
	"configureSrxFirewall":                        "srxfirewall",
	"configureVirtualRouterElement":               "virtualrouterelement",
	"copyIso":                                     "iso",
	"copyTemplate":                                "template",
	"createAccount":                               "account",
	"createAffinityGroup":                         "affinitygroup",
	"createAutoScalePolicy":                       "autoscalepolicy",
	"createAutoScaleVmGroup":                      "autoscalevmgroup",
	"createAutoScaleVmProfile":                    "autoscalevmprofile",
	"createCondition":                             "condition",
	"createCounter":                               "counter",
	"createDiskOffering":                          "diskoffering",
	"createDomain":                                "domain",
	"createEgressFirewallRule":                    "firewallrule",
	"createFirewallRule":                          "firewallrule",
	"createGlobalLoadBalancerRule":                "globalloadbalancerrule",
	"createInstanceGroup":                         "instancegroup",
	"createInternalLoadBalancerElement":           "internalloadbalancerelement",
	"createIpForwardingRule":                      "ipforwardingrule",
	"createLBHealthCheckPolicy":                   "lbhealthcheckpolicy",
	"createLBStickinessPolicy":                    "lbstickinesspolicy",
	"createLoadBalancer":                          "loadbalancer",
	"createLoadBalancerRule":                      "loadbalancerrule",
	"createLunOnFiler":                            "lunonfiler",
	"createNetwork":                               "network",
	"createNetworkACL":                            "networkacl",
	"createNetworkACLList":                        "networkacllist",
	"createNetworkOffering":                       "networkoffering",
	"createPhysicalNetwork":                       "physicalnetwork",
	"createPod":                                   "pod",
	"createPool":                                  "pool",
	"createPortForwardingRule":                    "portforwardingrule",
	"createPortableIpRange":                       "portableiprange",
	"createPrivateGateway":                        "privategateway",
	"createProject":                               "project",
	"createRemoteAccessVpn":                       "remoteaccessvpn",
	"createSSHKeyPair":                            "keypair",
	"createSecondaryStagingStore":                 "imagestore",
	"createSecurityGroup":                         "securitygroup",
	"createServiceOffering":                       "serviceoffering",
	"createSnapshot":                              "snapshot",
	"createSnapshotPolicy":                        "snapshotpolicy",
	"createStaticRoute":                           "staticroute",
	"createStorageNetworkIpRange":                 "storagenetworkiprange",
	"createStoragePool":                           "storagepool",
	"createTags":                                  "result",
	"createTemplate":                              "template",
	"createUser":                                  "user",
	"createVMSnapshot":                            "vmsnapshot",
	"createVPC":                                   "vpc",
	"createVPCOffering":                           "vpcoffering",
	"createVirtualRouterElement":                  "virtualrouterelement",
	"createVlanIpRange":                           "vlaniprange",
	"createVolume":                                "volume",
	"createVolumeOnFiler":                         "volumeonfiler",
	"createVpnConnection":                         "vpnconnection",
	"createVpnCustomerGateway":                    "vpncustomergateway",
	"createVpnGateway":                            "vpngateway",
	"createZone":                                  "zone",
	"dedicateCluster":                             "dedicatedcluster",
	"dedicateGuestVlanRange":                      "guestvlanrange",
	"dedicateHost":                                "dedicatedhost",
	"dedicatePod":                                 "dedicatedpod",
	"dedicatePublicIpRange":                       "publiciprange",
	"dedicateZone":                                "zone",
	"deleteAccount":                               "result",
	"deleteAccountFromProject":                    "result",
	"deleteAffinityGroup":                         "result",
	"deleteAlerts":                                "result",
	"deleteAutoScalePolicy":                       "result",
	"deleteAutoScaleVmGroup":                      "result",
	"deleteAutoScaleVmProfile":                    "result",
	"deleteCiscoAsa1000vResource":                 "result",
	"deleteCiscoNexusVSM":                         "result",
	"deleteCiscoVnmcResource":                     "result",
	"deleteCluster":                               "result",
	"deleteCondition":                             "result",
	"deleteCounter":                               "result",
	"deleteDiskOffering":                          "result",
	"deleteDomain":                                "result",
	"deleteEgressFirewallRule":                    "result",
	"deleteEvents":                                "result",
	"deleteExternalFirewall":                      "result",
	"deleteExternalLoadBalancer":                  "result",
	"deleteF5LoadBalancer":                        "result",
	"deleteFirewallRule":                          "result",
	"deleteGlobalLoadBalancerRule":                "result",
	"deleteHost":                                  "result",
	"deleteImageStore":                            "result",
	"deleteInstanceGroup":                         "result",
	"deleteIpForwardingRule":                      "result",
	"deleteIso":                                   "result",
	"deleteLBHealthCheckPolicy":                   "result",
	"deleteLBStickinessPolicy":                    "result",
	"deleteLoadBalancer":                          "result",
	"deleteLoadBalancerRule":                      "result",
	"deleteNetscalerLoadBalancer":                 "result",
	"deleteNetwork":                               "result",
	"deleteNetworkACL":                            "result",
	"deleteNetworkACLList":                        "result",
	"deleteNetworkDevice":                         "result",
	"deleteNetworkOffering":                       "result",
	"deleteNetworkServiceProvider":                "result",
	"deleteNiciraNvpDevice":                       "result",
	"deletePhysicalNetwork":                       "result",
	"deletePod":                                   "result",
	"deletePool":                                  "result",
	"deletePortForwardingRule":                    "result",
	"deletePortableIpRange":                       "result",
	"deletePrivateGateway":                        "result",
	"deleteProject":                               "result",
	"deleteProjectInvitation":                     "result",
	"deleteRemoteAccessVpn":                       "result",
	"deleteSSHKeyPair":                            "result",
	"deleteSecondaryStagingStore":                 "result",
	"deleteSecurityGroup":                         "result",
	"deleteServiceOffering":                       "result",
	"deleteSnapshot":                              "result",
	"deleteSnapshotPolicies":                      "result",
	"deleteSrxFirewall":                           "result",
	"deleteStaticRoute":                           "result",
	"deleteStorageNetworkIpRange":                 "result",
	"deleteStoragePool":                           "result",
	"deleteTags":                                  "result",
	"deleteTemplate":                              "result",
	"deleteTrafficMonitor":                        "result",
	"deleteTrafficType":                           "result",
	"deleteUcsManager":                            "result",
	"deleteUser":                                  "result",
	"deleteVMSnapshot":                            "result",
	"deleteVPC":                                   "result",
	"deleteVPCOffering":                           "result",
	"deleteVlanIpRange":                           "result",
	"deleteVolume":                                "result",
	"deleteVpnConnection":                         "result",
	"deleteVpnCustomerGateway":                    "result",
	"deleteVpnGateway":                            "result",
	"deleteZone":                                  "result",
	"deployVirtualMachine":                        "virtualmachine",
	"destroyLunOnFiler":                           "lunonfiler",
	"destroyRouter":                               "router",
	"destroySystemVm":                             "systemvm",
	"destroyVirtualMachine":                       "virtualmachine",
	"destroyVolumeOnFiler":                        "volumeonfiler",
	"detachIso":                                   "virtualmachine",
	"detachVolume":                                "volume",
	"disableAccount":                              "account",
	"disableAutoScaleVmGroup":                     "autoscalevmgroup",
	"disableCiscoNexusVSM":                        "cisconexusvsm",
	"disableStaticNat":                            "result",
	"disableUser":                                 "user",
	"disassociateIpAddress":                       "result",
	"disassociateUcsProfileFromBlade":             "ucsprofilefromblade",
	"dissociateLun":                               "lun",
	"enableAccount":                               "account",
	"enableAutoScaleVmGroup":                      "autoscalevmgroup",
	"enableCiscoNexusVSM":                         "cisconexusvsm",
	"enableStaticNat":                             "result",
	"enableStorageMaintenance":                    "storagepool",
	"enableUser":                                  "user",
	"extractIso":                                  "iso",
	"extractTemplate":                             "template",
	"extractVolume":                               "volume",
	"findHostsForMigration":                       "host",
	"findStoragePoolsForMigration":                "storagepool",
	"generateUsageRecords":                        "result",
	"getApiLimit":                                 "apilimit",
	"getCloudIdentifier":                          "cloudidentifier",
	"getUser":                                     "user",
	"getVMPassword":                               "vmpassword",
	"instantiateUcsTemplateAndAssocaciateToBlade": "ucstemplateandassocaciatetoblade",
	"ldapConfig":                                  "ldapconfig",
	"ldapRemove":                                  "ldapremove",
	"listAccounts":                                "account",
	"listAffinityGroupTypes":                      "affinitygrouptype",
	"listAffinityGroups":                          "affinitygroup",
	"listAlerts":                                  "alert",
	"listApis":                                    "api",
	"listAsyncJobs":                               "asyncjob",
	"listAutoScalePolicies":                       "autoscalepolicy",
	"listAutoScaleVmGroups":                       "autoscalevmgroup",
	"listAutoScaleVmProfiles":                     "autoscalevmprofile",
	"listBaremetalDhcp":                           "baremetaldhcp",
	"listBaremetalPxeServers":                     "baremetalpxeserver",
	"listCapabilities":                            "capability",
	"listCapacity":                                "capacity",
	"listCiscoAsa1000vResources":                  "ciscoasa1000vresource",
	"listCiscoNexusVSMs":                          "cisconexusvsm",
	"listCiscoVnmcResources":                      "ciscovnmcresource",
	"listClusters":                                "cluster",
	"listConditions":                              "condition",
	"listConfigurations":                          "configuration",
	"listCounters":                                "counter",
	"listDedicatedClusters":                       "dedicatedcluster",
	"listDedicatedGuestVlanRanges":                "dedicatedguestvlanrange",
	"listDedicatedHosts":                          "dedicatedhost",
	"listDedicatedPods":                           "dedicatedpod",
	"listDedicatedZones":                          "dedicatedzone",
	"listDeploymentPlanners":                      "deploymentplanner",
	"listDiskOfferings":                           "diskoffering",
	"listDomainChildren":                          "domain",
	"listDomains":                                 "domain",
	"listEgressFirewallRules":                     "firewallrule",
	"listEventTypes":                              "eventtype",
	"listEvents":                                  "event",
	"listExternalFirewalls":                       "externalfirewall",
	"listExternalLoadBalancers":                   "externalloadbalancer",
	"listF5LoadBalancerNetworks":                  "network",
	"listF5LoadBalancers":                         "f5loadbalancer",
	"listFirewallRules":                           "firewallrule",
	"listGlobalLoadBalancerRules":                 "globalloadbalancerrule",
	"listHosts":                                   "host",
	"listHostTags":                                "hosttag",
	"listHypervisorCapabilities":                  "hypervisorcapability",
	"listHypervisors":                             "hypervisor",
	"listImageStores":                             "imagestore",
	"listInstanceGroups":                          "instancegroup",
	"listInternalLoadBalancerElements":            "internalloadbalancerelement",
	"listInternalLoadBalancerVMs":                 "internalloadbalancervm",
	"listIpForwardingRules":                       "ipforwardingrule",
	"listIsoPermissions":                          "isopermission",
	"listIsos":                                    "iso",
	"listLBHealthCheckPolicies":                   "lbhealthcheckpolicy",
	"listLBStickinessPolicies":                    "lbstickinesspolicy",
	"listLoadBalancerRuleInstances":               "loadbalancerruleinstance",
	"listLoadBalancerRules":                       "loadbalancerrule",
	"listLoadBalancers":                           "loadbalancer",
	"listLunsOnFiler":                             "lunsonfiler",
	"listNetscalerLoadBalancerNetworks":           "network",
	"listNetscalerLoadBalancers":                  "netscalerloadbalancer",
	"listNetworkACLLists":                         "networkacllist",
	"listNetworkACLs":                             "networkacl",
	"listNetworkDevice":                           "networkdevice",
	"listNetworkIsolationMethods":                 "networkisolationmethod",
	"listNetworkOfferings":                        "networkoffering",
	"listNetworkServiceProviders":                 "networkserviceprovider",
	"listNetworks":                                "network",
	"listNiciraNvpDeviceNetworks":                 "network",
	"listNiciraNvpDevices":                        "niciranvpdevice",
	"listNics":                                    "nic",
	"listOsCategories":                            "oscategory",
	"listOsTypes":                                 "ostype",
	"listPhysicalNetworks":                        "physicalnetwork",
	"listPods":                                    "pod",
	"listPools":                                   "pool",
	"listPortForwardingRules":                     "portforwardingrule",
	"listPortableIpRanges":                        "portableiprange",
	"listPrivateGateways":                         "privategateway",
	"listProjectAccounts":                         "projectaccount",
	"listProjectInvitations":                      "projectinvitation",
	"listProjects":                                "project",
	"listPublicIpAddresses":                       "publicipaddress",
	"listRegions":                                 "region",
	"listRemoteAccessVpns":                        "remoteaccessvpn",
	"listResourceDetails":                         "resourcedetail",
	"listResourceLimits":                          "resourcelimit",
	"listRouters":                                 "router",
	"listS3s":                                     "s3",
	"listSSHKeyPairs":                             "sshkeypair",
	"listSecondaryStagingStores":                  "imagestore",
	"listSecurityGroups":                          "securitygroup",
	"listServiceOfferings":                        "serviceoffering",
	"listSnapshotPolicies":                        "snapshotpolicy",
	"listSnapshots":                               "snapshot",
	"listSrxFirewallNetworks":                     "network",
	"listSrxFirewalls":                            "srxfirewall",
	"listStaticRoutes":                            "staticroute",
	"listStorageNetworkIpRange":                   "storagenetworkiprange",
	"listStoragePools":                            "storagepool",
	"listStorageProviders":                        "storageprovider",
	"listStorageTags":                             "storagetag",
	"listSupportedNetworkServices":                "networkservice",
	"listSwifts":                                  "swift",
	"listSystemVms":                               "systemvm",
	"listTags":                                    "tag",
	"listTemplatePermissions":                     "templatepermission",
	"listTemplates":                               "template",
	"listTrafficMonitors":                         "trafficmonitor",
	"listTrafficTypeImplementors":                 "traffictypeimplementor",
	"listTrafficTypes":                            "traffictype",
	"listUcsBlades":                               "ucsblade",
	"listUcsManagers":                             "ucsmanager",
	"listUcsProfiles":                             "ucsprofile",
	"listUcsTemplates":                            "ucstemplate",
	"listUsageRecords":                            "usagerecord",
	"listUsageTypes":                              "usagetype",
	"listUsers":                                   "user",
	"listVMSnapshot":                              "vmsnapshot",
	"listVPCOfferings":                            "vpcoffering",
	"listVPCs":                                    "vpc",
	"listVirtualMachines":                         "virtualmachine",
	"listVirtualRouterElements":                   "virtualrouterelement",
	"listVlanIpRanges":                            "vlaniprange",
	"listVmwareDcs":                               "vmwaredc",
	"listVolumes":                                 "volume",
	"listVolumesOnFiler":                          "volumesonfiler",
	"listVpnConnections":                          "vpnconnection",
	"listVpnCustomerGateways":                     "vpncustomergateway",
	"listVpnGateways":                             "vpngateway",
	"listVpnUsers":                                "vpnuser",
	"listZones":                                   "zone",
	"lockAccount":                                 "account",
	"lockUser":                                    "user",
	"markDefaultZoneForAccount":                   "account",
	"migrateSystemVm":                             "systemvm",
	"migrateVirtualMachine":                       "virtualmachine",
	"migrateVirtualMachineWithVolume":             "virtualmachine",
	"migrateVolume":                               "volume",
	"modifyPool":                                  "pool",
	"prepareHostForMaintenance":                   "host",
	"prepareTemplate":                             "template",
	"rebootRouter":                                "router",
	"rebootSystemVm":                              "systemvm",
	"rebootVirtualMachine":                        "virtualmachine",
	"reconnectHost":                               "host",
	"recoverVirtualMachine":                       "virtualmachine",
	"refreshUcsBlades":                            "ucsblades",
	"registerIso":                                 "iso",
	"registerSSHKeyPair":                          "sshkeypair",
	"registerTemplate":                            "template",
	"registerUserKeys":                            "userkeys",
	"releaseDedicatedCluster":                     "result",
	"releaseDedicatedGuestVlanRange":              "result",
	"releaseDedicatedHost":                        "result",
	"releaseDedicatedPod":                         "result",
	"releaseDedicatedZone":                        "result",
	"releaseHostReservation":                      "result",
	"releasePublicIpRange":                        "result",
	"removeFromGlobalLoadBalancerRule":            "result",
	"removeFromLoadBalancerRule":                  "result",
	"removeIpFromNic":                             "result",
	"removeNicFromVirtualMachine":                 "virtualmachine",
	"removeRegion":                                "result",
	"removeResourceDetail":                        "result",
	"removeVmwareDc":                              "result",
	"removeVpnUser":                               "result",
	"replaceNetworkACLList":                       "result",
	"resetApiLimit":                               "apilimit",
	"resetPasswordForVirtualMachine":              "virtualmachine",
	"resetSSHKeyForVirtualMachine":                "virtualmachine",
	"resetVpnConnection":                          "vpnconnection",
	"resizeVolume":                                "volume",
	"restartNetwork":                              "network",
	"restartVPC":                                  "vpc",
	"restoreVirtualMachine":                       "virtualmachine",
	"revertToVMSnapshot":                          "virtualmachine",
	"revokeSecurityGroupEgress":                   "result",
	"revokeSecurityGroupIngress":                  "result",
	"scaleSystemVm":                               "systemvm",
	"scaleVirtualMachine":                         "result",
	"startInternalLoadBalancerVM":                 "internalloadbalancervm",
	"startRouter":                                 "router",
	"startSystemVm":                               "systemvm",
	"startVirtualMachine":                         "virtualmachine",
	"stopInternalLoadBalancerVM":                  "internalloadbalancervm",
	"stopRouter":                                  "router",
	"stopSystemVm":                                "systemvm",
	"stopVirtualMachine":                          "virtualmachine",
	"suspendProject":                              "project",
	"updateAccount":                               "account",
	"updateAutoScalePolicy":                       "autoscalepolicy",
	"updateAutoScaleVmGroup":                      "autoscalevmgroup",
	"updateAutoScaleVmProfile":                    "autoscalevmprofile",
	"updateCluster":                               "cluster",
	"updateConfiguration":                         "configuration",
	"updateDefaultNicForVirtualMachine":           "virtualmachine",
	"updateDiskOffering":                          "diskoffering",
	"updateDomain":                                "domain",
	"updateGlobalLoadBalancerRule":                "globalloadbalancerrule",
	"updateHost":                                  "host",
	"updateHostPassword":                          "result",
	"updateHypervisorCapabilities":                "hypervisorcapabilities",
	"updateInstanceGroup":                         "instancegroup",
	"updateIso":                                   "iso",
	"updateIsoPermissions":                        "result",
	"updateLoadBalancerRule":                      "loadbalancerrule",
	"updateNetwork":                               "network",
	"updateNetworkACLItem":                        "networkaclitem",
	"updateNetworkOffering":                       "networkoffering",
	"updateNetworkServiceProvider":                "networkserviceprovider",
	"updatePhysicalNetwork":                       "physicalnetwork",
	"updatePod":                                   "pod",
	"updatePortForwardingRule":                    "portforwardingrule",
	"updateProject":                               "project",
	"updateProjectInvitation":                     "result",
	"updateRegion":                                "region",
	"updateResourceCount":                         "resourcecount",
	"updateResourceLimit":                         "resourcelimit",
	"updateServiceOffering":                       "serviceoffering",
	"updateStorageNetworkIpRange":                 "storagenetworkiprange",
	"updateStoragePool":                           "storagepool",
	"updateTemplate":                              "template",
	"updateTemplatePermissions":                   "result",
	"updateTrafficType":                           "traffictype",
	"updateUser":                                  "user",
	"updateVMAffinityGroup":                       "virtualmachine",
	"updateVPC":                                   "vpc",
	"updateVPCOffering":                           "vpcoffering",
	"updateVirtualMachine":                        "virtualmachine",
	"updateVolume":                                "volume",
	"updateVpnCustomerGateway":                    "vpncustomergateway",
	"updateZone":                                  "zone",
	"uploadCustomCertificate":                     "customcertificate",
	"uploadVolume":                                "volume",
	"deleteOpenDaylightController":                "opendaylightcontroller",
	"upgradeRouterTemplate":                       "routertemplate",
	"addStratosphereSsp":                          "stratospheressp",
	"addGuestOs":                                  "guestos",
	"revertSnapshot":                              "snapshot",
	"addLdapConfiguration":                        "ldapconfiguration",
	"generateAlert":                               "result",
	"listBigSwitchVnsDevices":                     "bigswitchvnsdevice",
	"addGuestOsMapping":                           "guestosmapping",
	"configureOvsElement":                         "ovselement",
	"updateLBHealthCheckPolicy":                   "lbhealthcheckpolicy",
	"updateFirewallRule":                          "firewallrule",
	"removeGuestOs":                               "result",
	"configurePaloAltoFirewall":                   "paloaltofirewall",
	"updateVpnConnection":                         "vpnconnection",
	"updateVpnGateway":                            "vpngateway",
	"listSslCerts":                                "sslcert",
	"updateGuestOsMapping":                        "guestosmapping",
	"listPaloAltoFirewalls":                       "paloaltofirewall",
	"removeCertFromLoadBalancer":                  "result",
	"listOpenDaylightControllers":                 "opendaylightcontroller",
	"deleteLdapConfiguration":                     "ldapconfiguration",
	"listPaloAltoFirewallNetworks":                "network",
	"createServiceInstance":                       "serviceinstance",
	"addOpenDaylightController":                   "opendaylightcontroller",
	"updateEgressFirewallRule":                    "firewallrule",
	"updateGuestOs":                               "guestos",
	"deleteSslCert":                               "result",
	"addBigSwitchVnsDevice":                       "bigswitchvnsdevice",
	"deleteBigSwitchVnsDevice":                    "result",
	"ldapCreateAccount":                           "account",
	"assignCertToLoadBalancer":                    "result",
	"expungeVirtualMachine":                       "result",
	"removeGuestOsMapping":                        "result",
	"updateNetworkACLList":                        "result",
	"uploadSslCert":                               "sslcert",
	"updateLBStickinessPolicy":                    "lbstickinesspolicy",
	"listOvsElements":                             "ovselement",
	"listLdapConfigurations":                      "ldapconfiguration",
	"listLdapUsers":                               "ldapuser",
	"getVirtualMachineUserData":                   "virtualmachineuserdata",
	"updateIpAddress":                             "publicipaddress",
	"addPaloAltoFirewall":                         "paloaltofirewall",
	"importLdapUsers":                             "ldapuser",
	"deletePaloAltoFirewall":                      "result",
	"updateCloudToUseObjectStore":                 "imagestore",
	"listGuestOsMapping":                          "guestosmapping",
	"updateRemoteAccessVpn":                       "remoteaccessvpn",
	"updateLoadBalancer":                          "loadbalancer",
}

var CamelMap = map[string]string{
	"accept":                  "Accept",
	"accesskey":               "AccessKey",
	"account":                 "Account",
	"accountdetails":          "AccountDetails",
	"accountid":               "AccountId",
	"accounts":                "Accounts",
	"accounttype":             "AccountType",
	"aclid":                   "AclId",
	"acltype":                 "AclType",
	"action":                  "Action",
	"activeonly":              "ActiveOnly",
	"activeviewersessions":    "ActiveViewerSessions",
	"affinitygroup":           "AffinityGroup",
	"affinitygroupid":         "AffinityGroupId",
	"affinitygroupids":        "AffinityGroupIds",
	"affinitygroupnames":      "AffinityGroupNames",
	"affinitygrouptype":       "AffinityGroupType",
	"algorithm":               "Algorithm",
	"alert":                   "Alert",
	"allocated":               "Allocated",
	"allocatedonly":           "AllocatedOnly",
	"allocationstate":         "AllocationState",
	"allowusercreateprojects": "AllowUserCreateProjects",
	"api":                          "Api",
	"apiallowed":                   "ApiAllowed",
	"apiissued":                    "ApiIssued",
	"apikey":                       "ApiKey",
	"apilimit":                     "ApiLimit",
	"apilimitinterval":             "ApiLimitInterval",
	"apilimitmax":                  "ApiLimitMax",
	"applied":                      "Applied",
	"associatednetworkid":          "AssociatedNetworkId",
	"associatednetworkname":        "AssociatedNetworkName",
	"asyncjob":                     "AsyncJob",
	"attached":                     "Attached",
	"autoscalepolicy":              "AutoScalePolicy",
	"autoscaleuserid":              "AutoScaleUserId",
	"autoscalevmgroup":             "AutoScaleVmGroup",
	"autoscalevmprofile":           "AutoScaleVmProfile",
	"availability":                 "Availability",
	"available":                    "Available",
	"averageload":                  "AverageLoad",
	"baremetaldhcp":                "BaremetalDhcp",
	"baremetalpxekickstartserver":  "BaremetalPxeKickStartServer",
	"baremetalpxepingserver":       "BaremetalPxePingServer",
	"baremetalpxeserver":           "BaremetalPxeServer",
	"baremetalrcturl":              "BaremetalRctUrl",
	"bigswitchdevicename":          "BigSwitchDeviceName",
	"bigswitchvnsdevice":           "BigSwitchVnsDevice",
	"bits":                         "Bits",
	"bladedn":                      "Bladedn",
	"bladeid":                      "BladeId",
	"bootable":                     "Bootable",
	"brocadedevicename":            "BroadcastDeviceName",
	"broadcastdomainrange":         "BroadcastDomainRange",
	"broadcastdomaintype":          "BroadcastDomainType",
	"broadcasturi":                 "BroadcastUri",
	"bucket":                       "Bucket",
	"bytesreadrate":                "BytesReadRate",
	"byteswriterate":               "BytesWriteRate",
	"cachemode":                    "CacheMode",
	"canenableindividualservice":   "CanEnableIndividualService",
	"canusefordeploy":              "CanUseForDeploy",
	"capabilities":                 "Capabilities",
	"capability":                   "Capability",
	"capacity":                     "Capacity",
	"capacitybytes":                "CapacityBytes",
	"capacityiops":                 "CapacityIops",
	"capacitytotal":                "CapacityTotal",
	"capacityused":                 "CapacityUsed",
	"category":                     "Category",
	"certchain":                    "CertChain",
	"certid":                       "CertId",
	"certificate":                  "Certificate",
	"chaininfo":                    "ChainInfo",
	"changecidr":                   "changeCidr",
	"checksum":                     "Checksum",
	"cidr":                         "Cidr",
	"cidrlist":                     "CidrList",
	"ciscoasa1000vresource":        "CiscoAsa1000vResource",
	"cisconexusvsm":                "CiscoNexusVsm",
	"ciscovnmcresource":            "CiscoVnmcResource",
	"cleanup":                      "Cleanup",
	"cloudidentifier":              "CloudIdentifier",
	"cloudstackversion":            "CloudStackVersion",
	"cluster":                      "Cluster",
	"clusterid":                    "ClusterId",
	"clustername":                  "ClusterName",
	"clustertype":                  "ClusterType",
	"cmd":                          "Cmd",
	"condition":                    "Condition",
	"conditionid":                  "ConditionId",
	"conditionids":                 "ConditionIds",
	"conditions":                   "Conditions",
	"configuration":                "Configuration",
	"connectiontimeout":            "ConnectionTimeout",
	"conservemode":                 "ConserveMode",
	"count":                        "Count",
	"counter":                      "Counter",
	"counterid":                    "CounterId",
	"counterparam":                 "CounterParam",
	"cpuallocated":                 "CpuAllocated",
	"cpuavailable":                 "CpuAvailable",
	"cpulimit":                     "CpuLimit",
	"cpunumber":                    "CpuNumber",
	"cpuovercommitratio":           "CpuOverCommitRatio",
	"cpusockets":                   "CpuSockets",
	"cpuspeed":                     "CpuSpeed",
	"cputotal":                     "CpuTotal",
	"cpuused":                      "CpuUsed",
	"cpuwithoverprovisioning":      "CpuWithOverProvisioning",
	"created":                      "Created",
	"crosszones":                   "CrossZones",
	"current":                      "Current",
	"customcertificate":            "CustomCertificate",
	"customdiskofferingmaxsize":    "CustomDiskOfferingMaxSize",
	"customdiskofferingminsize":    "CustomDiskOfferingminSize",
	"customer":                     "Customer",
	"customid":                     "CustomId",
	"customized":                   "Customized",
	"customizediops":               "CustomizedIops",
	"dedicatedcluster":             "DedicatedCluster",
	"dedicatedguestvlanrange":      "DedicatedGuestVlanRange",
	"dedicatedhost":                "DedicatedHost",
	"dedicatedpod":                 "DedicatedPod",
	"dedicatedzone":                "DedicatedZone",
	"defaultnicforvirtualmachine":  "DefaultNicForVirtualMachine",
	"defaultuse":                   "DefaultUse",
	"defaultzoneforaccount":        "DefaultZoneForAccount",
	"defaultzoneid":                "DefaultZoneId",
	"deploymentplanner":            "DeploymentPlanner",
	"description":                  "Description",
	"destinationphysicalnetworkid": "DestinationPhysicalNetworkId",
	"destroyed":                    "Destroyed",
	"destroyvmgraceperiod":         "DestroyVmGracePeriod",
	"destzoneid":                   "DestZoneId",
	"details":                      "Details",
	"deviceid":                     "DeviceId",
	"dhcpprovider":                 "DhcpProvider",
	"dhcpservertype":               "DhcpServerType",
	"disconnected":                 "Disconnected",
	"diskbytesreadrate":            "DiskBytesReadRate",
	"diskbyteswriterate":           "DiskBytesWriteRate",
	"diskiopsreadrate":             "DiskIopsReadRate",
	"diskiopswriterate":            "DiskIopsWriteRate",
	"diskioread":                   "DiskIoRead",
	"diskiowrite":                  "DiskIoWrite",
	"diskkbsread":                  "DiskKbsRead",
	"diskkbswrite":                 "DiskKbsWrite",
	"diskofferingdisplaytext":      "DiskOfferingDisplayText",
	"diskoffering":                 "DiskOffering",
	"diskofferingid":               "DiskOfferingId",
	"diskofferingname":             "DiskOfferingName",
	"disksize":                     "DiskSize",
	"disksizeallocated":            "DiskSizeAllocated",
	"disksizetotal":                "DiskSizeTotal",
	"disksizeused":                 "DiskSizeUsed",
	"displayname":                  "DisplayName",
	"displaynetwork":               "DisplayNetwork",
	"displayoffering":              "DisplayOffering",
	"displaytext":                  "DisplayText",
	"displayvm":                    "DisplayVm",
	"displayvolume":                "DisplayVolume",
	"distributedvpcrouter":         "DistributedVpcRouter",
	"dns1":                         "Dns1",
	"dns2":                         "Dns2",
	"dnssearchorder":               "Dnssearchorder",
	"domain":                       "Domain",
	"domainchildren":               "DomainChildren",
	"domainid":                     "DomainId",
	"domainname":                   "DomainName",
	"domainsuffix":                 "DomainSuffix",
	"dpd":                          "Dpd",
	"duration":                     "Duration",
	"egressdefaultpolicy":          "EgressDefaultPolicy",
	"egressfirewallrule":           "EgressFirewallRule",
	"egressrule":                   "EgressRule",
	"email":                        "Email",
	"enabled":                      "Enabled",
	"encryptedpassword":            "EncryptedPassword",
	"enddate":                      "EndDate",
	"endip":                        "EndIp",
	"endipv6":                      "EndIpv6",
	"endpoint":                     "EndPoint",
	"endport":                      "EndPort",
	"entrytime":                    "EntryTime",
	"esplifetime":                  "EspLifeTime",
	"esppolicy":                    "EspPolicy",
	"event":                        "Event",
	"events":                       "Events",
	"eventtype":                    "EventType",
	"excludezones":                 "ExcludeZones",
	"expireafter":                  "ExpireAfter",
	"expunge":                      "Expunge",
	"externalfirewall":             "ExternalFirewall",
	"externalloadbalancer":         "ExternalLoadBalancer",
	"extractid":                    "ExtractId",
	"extractmode":                  "ExtractMode",
	"f5loadbalancer":               "F5LoadBalancer",
	"f5loadbalancernetwork":        "F5LoadBalancerNetwork",
	"fetchlatest":                  "FetchLatest",
	"fingerprint":                  "FingerPrint",
	"firewallrule":                 "FirewallRule",
	"firstname":                    "FirstName",
	"forced":                       "Forced",
	"forcedestroylocalstorage":     "ForceDestroyLocalStorage",
	"fordisplay":                   "ForDisplay",
	"forloadbalancing":             "ForLoadBalancing",
	"format":                       "Format",
	"forvirtualnetwork":            "ForVirtualNetwork",
	"forvpc":                       "ForVpc",
	"fwdevicecapacity":             "FwDeviceCapacity",
	"fwdeviceid":                   "FwDeviceId",
	"fwdevicename":                 "FwDeviceName",
	"fwdevicestate":                "FwDeviceState",
	"gateway":                      "Gateway",
	"gatewayid":                    "GatewayId",
	"globalloadbalancerrule":       "GlobalLoadBalancerRule",
	"gpugroup":                     "GpuGroup",
	"group":                        "Group",
	"groupid":                      "GroupId",
	"groups":                       "Groups",
	"gslbdomainname":               "GslbDomainName",
	"gslblbmethod":                 "GslblbMethod",
	"gslblbruleweightsmap":         "GslblbRuleweightsmap",
	"gslbprovider":                 "GslbProvider",
	"gslbproviderprivateip":        "GslbProviderPrivateIp",
	"gslbproviderpublicip":         "GslbProviderPublicIp",
	"gslbserviceenabled":           "GslbServiceEnabled",
	"gslbservicetype":              "GslbServiceType",
	"gslbstickysessionmethodname":  "GslbStickySessionMethodName",
	"guestcidraddress":             "GuestCidrAddress",
	"guestipaddress":               "GuestIpAddress",
	"guestiptype":                  "GuestIpType",
	"guestmacaddress":              "GuestMacAddress",
	"guestnetmask":                 "GuestNetmask",
	"guestnetworkid":               "GuestNetworkId",
	"guestos":                      "GuestOs",
	"guestosid":                    "GuestOsId",
	"guestosmapping":               "GuestOsMapping",
	"guestvlanrange":               "GuestVlanRange",
	"guestvmcidr":                  "GuestVmCidr",
	"guestvswitchname":             "GuestVswitchName",
	"guestvswitchtype":             "GuestVswitchType",
	"haenable":                     "HaEnable",
	"hahost":                       "HaHost",
	"haschild":                     "HasChild",
	"hasenoughcapacity":            "HasEnoughCapacity",
	"healthcheckpolicy":            "HealthCheckPolicy",
	"healthythreshold":             "HealthyThreshold",
	"host":                         "Host",
	"hostid":                       "HostId",
	"hostname":                     "HostName",
	"hosttag":                      "HostTag",
	"hosttags":                     "HostTags",
	"hypervisor":                   "Hypervisor",
	"hypervisorcapabilities":       "HypervisorCapabilities",
	"hypervisorcapability":         "HypervisorCapability",
	"hypervisorsnapshotreserve":    "HypervisorSnapshotReserve",
	"hypervisortype":               "HypervisorType",
	"hypervisorversion":            "HypervisorVersion",
	"hypervnetworklabel":           "HypervNetworkLabel",
	"icmpcode":                     "IcmpCode",
	"icmptype":                     "IcmpType",
	"id":                           "Id",
	"ids":                          "Ids",
	"ikelifetime":                  "IkeLifeTime",
	"ikepolicy":                    "IkePolicy",
	"imagestore":                   "ImageStore",
	"imagestoreuuid":               "ImageStoreUuid",
	"includezones":                 "IncludeZones",
	"ingressrule":                  "IngressRule",
	"inline":                       "Inline",
	"insideportprofile":            "InsidePortProfile",
	"instancegroup":                "InstanceGroup",
	"instancename":                 "InstanceName",
	"instanceport":                 "InstancePort",
	"internaldns1":                 "InternalDns1",
	"internaldns2":                 "InternalDns2",
	"internalloadbalancerelement":  "InternalLoadBalancerElement",
	"internalloadbalancervm":       "InternalLoadBalancerVm",
	"interval":                     "Interval",
	"intervaltime":                 "IntervalTime",
	"intervaltype":                 "IntervalType",
	"iopsreadrate":                 "IopsReadRate",
	"iopswriterate":                "IopsWriteRate",
	"ip6address":                   "Ip6Address",
	"ip6cidr":                      "Ip6Cidr",
	"ip6dns1":                      "Ip6Dns1",
	"ip6dns2":                      "Ip6Dns2",
	"ip6gateway":                   "Ip6Gateway",
	"ipaddress":                    "IpAddress",
	"ipaddressid":                  "IpAddressId",
	"ipavailable":                  "IpAvailable",
	"ipforwardingrule":             "IpForwardingRule",
	"iplimit":                      "IpLimit",
	"iprange":                      "IpRange",
	"ipsecpsk":                     "IpsecPsk",
	"iptonetworklist":              "IpToNetworkList",
	"iptonic":                      "IpToNic",
	"iptotal":                      "IpTotal",
	"isasync":                      "IsAsync",
	"iscallerchilddomain":          "IsCallerChildDomain",
	"iscleanuprequired":            "IsCleanupRequired",
	"iscustomized":                 "IsCustomized",
	"iscustomizediops":             "IsCustomizedIops",
	"isdefault":                    "IsDefault",
	"isdynamicallyscalable":        "IsDynamicallyScalable",
	"isexclusivegslbprovider":      "IsExclusiveGslbProvider",
	"isextractable":                "IsExtractable",
	"isfeatured":                   "IsFeatured",
	"islocalstorageactive":         "IsLocalStorageActive",
	"iso":                          "Iso",
	"isodisplaytext":               "IsoDisplayText",
	"isofilter":                    "Isofilter",
	"isoid":                        "IsoId",
	"isolatedpvlan":                "IsolatedPvlan",
	"isolationmethod":              "IsolationMethod",
	"isolationmethods":             "IsolationMethods",
	"isolationuri":                 "IsolationUri",
	"isoname":                      "IsoName",
	"isopermission":                "IsoPermission",
	"ispersistent":                 "IsPersistent",
	"ispermission":                 "IsPermission",
	"isportable":                   "IsPortable",
	"ispublic":                     "IsPublic",
	"isready":                      "IsReady",
	"isrecursive":                  "IsRecursive",
	"isredundantrouter":            "IsRedundantRouter",
	"isrouting":                    "IsRouting",
	"issourcenat":                  "IsSourceNat",
	"isstaticnat":                  "IsStaticNat",
	"issystem":                     "IsSystem",
	"istagged":                     "IsTagged",
	"isuserdefined":                "IsUserDefined",
	"isvolatile":                   "IsVolatile",
	"jobid":                        "JobId",
	"jobinstanceid":                "JobInstanceId",
	"jobinstancetype":              "JobInstanceType",
	"jobprocstatus":                "JobProcStatus",
	"jobresult":                    "JobResult",
	"jobresultcode":                "JobResultCode",
	"jobresulttype":                "JobResultType",
	"jobstatus":                    "JobStatus",
	"jsonresponse":                 "JsonResponse",
	"keepaliveenabled":             "KeepaliveEnabled",
	"key":                          "Key",
	"keyboard":                     "Keyboard",
	"keypair":                      "KeyPair",
	"keyword":                      "Keyword",
	"kvmnetworklabel":              "KvmNetworkLabel",
	"kvmsnapshotenabled":           "KvmSnapshotEnabled",
	"l3gatewayserviceuuid":         "L3GatewayServiceUuid",
	"lastname":                     "LastName",
	"lastpinged":                   "LastPinged",
	"lbdevicecapacity":             "LbDeviceCapacity",
	"lbdevicededicated":            "LbDeviceDedicated",
	"lbdeviceid":                   "LbDeviceId",
	"lbdevicename":                 "LbDeviceName",
	"lbdevicestate":                "LbDeviceState",
	"lbhealthcheckpolicy":          "LbHealthCheckPolicy",
	"lbruleid":                     "LbRuleId",
	"lbstickinesspolicy":           "LbStickinessPolicy",
	"lbvmipaddresses":              "LbVmIpAddresses",
	"lbvmips":                      "LbVmIps",
	"ldapconfig":                   "LdapConfig",
	"ldapconfiguration":            "LdapConfiguration",
	"ldapremove":                   "LdapRemove",
	"ldapuser":                     "LdapUser",
	"leftnetworkid":                "LeftNetworkId",
	"level":                        "Level",
	"limitcpuuse":                  "LimitCpuUse",
	"linklocalip":                  "LinkLocalIp",
	"linklocalmacaddress":          "LinkLocalMacAddress",
	"linklocalnetmask":             "LinkLocalNetmask",
	"linklocalnetworkid":           "LinkLocalNetworkId",
	"listall":                      "ListAll",
	"listtype":                     "ListType",
	"livemigrate":                  "LiveMigrate",
	"loadbalancer":                 "LoadBalancer",
	"loadbalancerinstance":         "LoadBalancerInstance",
	"loadbalancerrule":             "LoadBalancerRule",
	"loadbalancerruleinstance":     "LoadBalancerRuleInstance",
	"loadbalancerrulelist":         "LoadBalancerRuleList",
	"localstorageenabled":          "LocalStorageEnabled",
	"lock":                         "Lock",
	"lun":                          "Lun",
	"lunonfiler":                   "LunOnFiler",
	"lunsonfiler":                  "LunsOnFiler",
	"macaddress":                   "MacAddress",
	"managed":                      "Managed",
	"managedstate":                 "ManagedState",
	"managementserverid":           "ManagementServerId",
	"max":                          "Max",
	"maxconnections":               "MaxConnections",
	"maxdatavolumeslimit":          "MaxDataVolumesLimit",
	"maxerrorretry":                "MaxErrorRetry",
	"maxguestslimit":               "MaxGuestsLimit",
	"maxhostspercluster":           "MaxHostsperCluster",
	"maxiops":                      "MaxIops",
	"maxmembers":                   "MaxMembers",
	"maxsnaps":                     "MaxSnaps",
	"memory":                       "Memory",
	"memoryallocated":              "MemoryAllocated",
	"memoryavailable":              "MemoryAvailable",
	"memorylimit":                  "MemoryLimit",
	"memoryovercommitratio":        "MemoryOverCommitRatio",
	"memorytotal":                  "MemoryTotal",
	"memoryused":                   "MemoryUsed",
	"message":                      "Message",
	"methodname":                   "MethodName",
	"migrateto":                    "MigrateTo",
	"miniops":                      "MinIops",
	"minmembers":                   "MinMembers",
	"mode":                         "Mode",
	"name":                         "Name",
	"netmask":                      "Netmask",
	"netscalerloadbalancer":        "NetScalerLoadBalancer",
	"netscalerloadbalancernetwork": "NetScalerLoadBalancerNetwork",
	"network":                      "Network",
	"networkacl":                   "NetworkAcl",
	"networkaclitem":               "NetworkAclItem",
	"networkacllist":               "NetworkAclList",
	"networkavailable":             "NetworkAvailable",
	"networkcidr":                  "NetworkCidr",
	"networkdevice":                "NetworkDevice",
	"networkdeviceparameterlist":   "NetworkDeviceParameterList",
	"networkdevicetype":            "NetworkDeviceType",
	"networkdomain":                "NetworkDomain",
	"networkid":                    "NetworkId",
	"networkids":                   "NetworkIds",
	"networkisolationmethod":       "NetworkIsolationMethod",
	"networkkbsread":               "NetworkKbsRead",
	"networkkbswrite":              "NetworkKbsWrite",
	"networklimit":                 "NetworkLimit",
	"networkname":                  "NetworkName",
	"networkoffering":              "NetworkOffering",
	"networkofferingavailability":  "NetworkOfferingAvailability",
	"networkofferingconservemode":  "NetworkOfferingconserveMode",
	"networkofferingdisplaytext":   "NetworkOfferingDisplayText",
	"networkofferingid":            "NetworkOfferingId",
	"networkofferingname":          "NetworkOfferingName",
	"networkrate":                  "NetworkRate",
	"networkservice":               "NetworkService",
	"networkserviceprovider":       "NetworkServiceProvider",
	"networkspeed":                 "NetworkSpeed",
	"networktotal":                 "NetworkTotal",
	"networktype":                  "NetworkType",
	"newname":                      "NewName",
	"nic":                          "Nic",
	"nicid":                        "NicId",
	"niciradevicename":             "NiciraDeviceName",
	"niciranvpdevice":              "NiciraNvpDevice",
	"niciranvpdevicenetwork":       "NiciraNvpDeviceNetwork",
	"nspid":                        "NspId",
	"number":                       "Number",
	"numretries":                   "NumRetries",
	"nvpdeviceid":                  "NvpDeviceId",
	"offerha":                      "OfferHa",
	"offeringid":                   "OfferingId",
	"op":                           "Op",
	"opendaylightcontroller":  "OpenDaylightController",
	"openfirewall":            "OpenFirewall",
	"oscategory":              "OsCategory",
	"oscategoryid":            "OsCategoryId",
	"oscategoryname":          "OsCategoryName",
	"osdisplayname":           "OsDisplayName",
	"osnameforhypervisor":     "OsNameForHypervisor",
	"ostype":                  "OsType",
	"ostypeid":                "OsTypeId",
	"ostypename":              "OsTypeName",
	"otherdeployparams":       "OtherDeployParams",
	"overprovisionfactor":     "OverProvisionFactor",
	"ovselement":              "OvsElement",
	"page":                    "Page",
	"pagesize":                "PageSize",
	"paloaltofirewall":        "PaloAltoFirewall",
	"paloaltofirewallnetwork": "PaloAltoFirewallNetwork",
	"param":                   "Param",
	"params":                  "Params",
	"parent":                  "Parent",
	"parentname":              "ParentName",
	"parentdomainid":          "ParentDomainId",
	"parentdomainname":        "ParentDomainName",
	"parentid":                "ParentId",
	"passive":                 "Passive",
	"password":                "Password",
	"passwordenabled":         "PasswordEnabled",
	"path":                    "Path",
	"pcidevicepath":           "PciDevicePath",
	"percentused":             "PercentUsed",
	"physicalnetwork":         "PhysicalNetwork",
	"physicalnetworkid":       "PhysicalNetworkId",
	"physicalsize":            "PhysicalSize",
	"pingcifspassword":        "PingCifsPassword",
	"pingcifsusername":        "PingCifsUserName",
	"pingdir":                 "PingDir",
	"pingpath":                "PingPath",
	"pingstorageserverip":     "PingStorageServerIp",
	"pod":                              "Pod",
	"podid":                            "PodId",
	"podids":                           "PodIds",
	"podname":                          "PodName",
	"policyid":                         "PolicyId",
	"pool":                             "Pool",
	"poolid":                           "PoolId",
	"port":                             "Port",
	"portforwardingrule":               "PortForwardingRule",
	"portableipaddress":                "PortableIpAddress",
	"portableiprange":                  "PortableIpRange",
	"portableipserviceenabled":         "PortableIpServiceEnabled",
	"presharedkey":                     "PreSharedKey",
	"primarystorageavailable":          "PrimaryStorageAvailable",
	"primarystoragelimit":              "PrimaryStorageLimit",
	"primarystoragetotal":              "PrimaryStorageTotal",
	"principal":                        "Principal",
	"privateendport":                   "PrivateEndPort",
	"privategateway":                   "PrivateGateway",
	"privateinterface":                 "PrivateInterface",
	"privateip":                        "PrivateIp",
	"privatekey":                       "PrivateKey",
	"privatemacaddress":                "PrivateMacAddress",
	"privatenetmask":                   "PrivateNetmask",
	"privateport":                      "PrivatePort",
	"privatezone":                      "PrivateZone",
	"profiledn":                        "Profiledn",
	"project":                          "Project",
	"projectaccount":                   "ProjectAccount",
	"projectavailable":                 "ProjectAvailable",
	"projectid":                        "ProjectId",
	"projectids":                       "ProjectIds",
	"projectinviterequired":            "ProjectinviteRequired",
	"projectinvitation":                "ProjectInvitation",
	"projectlimit":                     "ProjectLimit",
	"projecttotal":                     "ProjectTotal",
	"protocol":                         "Protocol",
	"provider":                         "Provider",
	"providername":                     "ProviderName",
	"providertype":                     "ProviderType",
	"provisioningtype":                 "ProvisioningType",
	"publicendport":                    "PublicEndPort",
	"publicinterface":                  "PublicInterface",
	"publicip":                         "PublicIp",
	"publicipaddress":                  "PublicIpAddress",
	"publicipid":                       "PublicIpId",
	"publiciprange":                    "PublicIpRange",
	"publickey":                        "PublicKey",
	"publicmacaddress":                 "PublicMacAddress",
	"publicnetmask":                    "PublicNetmask",
	"publicnetworkid":                  "PublicNetworkId",
	"publicport":                       "PublicPort",
	"publicvswitchname":                "PublicVswitchName",
	"publicvswitchtype":                "PublicVswitchType",
	"publiczone":                       "PublicZone",
	"purpose":                          "Purpose",
	"pxeservertype":                    "PxeServerType",
	"quiescevm":                        "QuiesceVm",
	"quiettime":                        "QuietTime",
	"rawusage":                         "RawUsage",
	"receivedbytes":                    "ReceivedBytes",
	"redundantstate":                   "RedundantState",
	"region":                           "Region",
	"regionid":                         "RegionId",
	"regionlevelvpc":                   "RegionlevelVpc",
	"regionsecondaryenabled":           "RegionSecondaryEnabled",
	"registered":                       "Registered",
	"related":                          "Related",
	"relationaloperator":               "RelationalOperator",
	"remoteaccessvpn":                  "RemoteAccessVpn",
	"removed":                          "Removed",
	"requiresstoragemotion":            "RequiresStorageMotion",
	"requireshvm":                      "RequiresHvm",
	"requiresupgrade":                  "RequiresUpgrade",
	"reservediprange":                  "ReservedIpRange",
	"resourcecount":                    "ResourceCount",
	"resourcedetail":                   "ResourceDetail",
	"resourcedetails":                  "ResourceDetails",
	"resourceid":                       "ResourceId",
	"resourceids":                      "ResourceIds",
	"resourcelimit":                    "ResourceLimit",
	"resourcestate":                    "ResourceState",
	"resourcetype":                     "ResourceType",
	"response":                         "Response",
	"responsetimeout":                  "ResponseTimeout",
	"restartrequired":                  "ReStartRequired",
	"result":                           "Result",
	"resultstring":                     "ResultString",
	"revertable":                       "Revertable",
	"rightnetworkid":                   "RightNetworkId",
	"role":                             "Role",
	"rootdeviceid":                     "RootDeviceId",
	"rootdevicetype":                   "RootDeviceType",
	"rootdisksize":                     "RootDiskSize",
	"router":                           "Router",
	"routertemplate":                   "RouterTemplate",
	"ruleid":                           "RuleId",
	"s2scustomergatewayid":             "S2sCustomerGatewayId",
	"s2svpngatewayid":                  "S2sVpnGatewayId",
	"s3":                               "S3",
	"scaledownpolicies":                "ScaleDownPolicies",
	"scaledownpolicyids":               "ScaleDownPolicyIds",
	"scaleuppolicies":                  "ScaleUpPolicies",
	"scaleuppolicyids":                 "ScaleUpPolicyIds",
	"schedule":                         "Schedule",
	"scheme":                           "Scheme",
	"scope":                            "Scope",
	"scriptsversion":                   "ScriptsVersion",
	"secondaryip":                      "SecondaryIp",
	"secondarystagingstore":            "SecondaryStagingStore",
	"secondarystorage":                 "SecondaryStorage",
	"secondarystorageavailable":        "SecondaryStorageAvailable",
	"secondarystoragelimit":            "SecondaryStorageLimit",
	"secondarystoragetotal":            "SecondaryStorageTotal",
	"secretkey":                        "SecretKey",
	"securitygroup":                    "SecurityGroup",
	"securitygroupegress":              "SecurityGroupEgress",
	"securitygroupenabled":             "SecurityGroupEnabled",
	"securitygroupid":                  "SecurityGroupId",
	"securitygroupids":                 "SecurityGroupIds",
	"securitygroupingress":             "SecurityGroupIngress",
	"securitygroupname":                "SecurityGroupName",
	"securitygroupnames":               "SecurityGroupNames",
	"securitygroupsenabled":            "SecurityGroupsEnabled",
	"sent":                             "Sent",
	"sentbytes":                        "SentBytes",
	"service":                          "Service",
	"servicecapabilitylist":            "ServiceCapabilityList",
	"serviceinstance":                  "ServiceInstance",
	"servicelist":                      "ServiceList",
	"serviceoffering":                  "ServiceOffering",
	"serviceofferingdetails":           "ServiceOfferingDetails",
	"serviceofferingdisplaytext":       "ServiceOfferingDisplayText",
	"serviceofferingid":                "ServiceOfferingId",
	"serviceofferingname":              "ServiceOfferingName",
	"serviceproviderlist":              "ServiceProviderList",
	"servicestate":                     "ServiceState",
	"sessionkey":                       "SessionKey",
	"showcapacities":                   "ShowCapacities",
	"showremoved":                      "ShowRemoved",
	"shrinkok":                         "ShrinkOk",
	"signature":                        "Signature",
	"since":                            "Since",
	"size":                             "Size",
	"snapshot":                         "Snapshot",
	"snapshotavailable":                "SnapshotAvailable",
	"snapshotid":                       "SnapshotId",
	"snapshotlimit":                    "SnapshotLimit",
	"snapshotmemory":                   "SnapshotMemory",
	"snapshotpolicy":                   "SnapshotPolicy",
	"snapshottotal":                    "SnapshotTotal",
	"snapshottype":                     "SnapshotType",
	"sockettimeout":                    "SocketTimeout",
	"solidfireaccountid":               "SolidFireAccountId",
	"solidfirevolumeaccessgroupid":     "SolidFireVolumeAccessGroupId",
	"solidfirevolumeiscsiname":         "SolidFireVolumeIscsiName",
	"solidfirevolumesize":              "SolidFireVolumeSize",
	"sortby":                           "SortBy",
	"sortkey":                          "SortKey",
	"source":                           "Source",
	"sourceipaddress":                  "SourceIpAddress",
	"sourceipaddressnetworkid":         "SourceIpAddressNetworkId",
	"sourcenatsupported":               "Sourcenatsupported",
	"sourceport":                       "SourcePort",
	"sourcetemplateid":                 "SourceTemplateId",
	"sourcezoneid":                     "SourceZoneId",
	"specifyipranges":                  "SpecifyIpRanges",
	"specifyvlan":                      "SpecifyVlan",
	"srxfirewall":                      "SrxFirewall",
	"srxfirewallnetwork":               "SrxFirewallNetwork",
	"sshkeypair":                       "SshKeyPair",
	"sshkeyenabled":                    "SshKeyEnabled",
	"sslcert":                          "SslCert",
	"start":                            "Start",
	"startdate":                        "StartDate",
	"startip":                          "StartIp",
	"startipv6":                        "StartIpv6",
	"startport":                        "StartPort",
	"startvm":                          "StartVm",
	"state":                            "State",
	"staticroute":                      "StaticRoute",
	"status":                           "Status",
	"stickinesspolicy":                 "StickinessPolicy",
	"storage":                          "Storage",
	"storagecapabilities":              "StorageCapabilities",
	"storageid":                        "StorageId",
	"storagemaintenance":               "StorageMaintenance",
	"storagemotionenabled":             "StoragemotionEnabled",
	"storagenetworkiprange":            "StorageNetworkIpRange",
	"storagepool":                      "StoragePool",
	"storageprovider":                  "StorageProvider",
	"storagetag":                       "StorageTag",
	"storagetype":                      "StorageType",
	"stratospheressp":                  "StratoSphereSsp",
	"strechedl2subnet":                 "StrechedL2Subnet",
	"subdomainaccess":                  "SubDomainAccess",
	"success":                          "Success",
	"suitableformigration":             "SuitableForMigration",
	"supportelb":                       "SupportELB",
	"supportedservices":                "SupportedServices",
	"supportsregionlevelvpc":           "SupportsRegionLevelVpc",
	"supportsstrechedl2subnet":         "SupportsStrechedL2Subnet",
	"swift":                            "Swift",
	"systemvm":                         "SystemVm",
	"systemvmtype":                     "SystemVmType",
	"tag":                              "Tag",
	"tags":                             "Tags",
	"template":                         "Template",
	"templateavailable":                "TemplateAvailable",
	"templatedisplaytext":              "TemplateDisplayText",
	"templatefilter":                   "Templatefilter",
	"templateid":                       "TemplateId",
	"templatelimit":                    "TemplateLimit",
	"templatename":                     "TemplateName",
	"templatepermission":               "TemplatePermission",
	"templatetag":                      "Templatetag",
	"templatetotal":                    "TemplateTotal",
	"templatetype":                     "TemplateType",
	"tenantuuid":                       "TenantUuid",
	"tftpdir":                          "TftpDir",
	"threshold":                        "Threshold",
	"timeout":                          "Timeout",
	"timezone":                         "TimeZone",
	"token":                            "Token",
	"trafficmonitor":                   "TrafficMonitor",
	"traffictype":                      "TrafficType",
	"traffictypeimplementor":           "TrafficTypeImplementor",
	"transportzoneuuid":                "TransportZoneUuid",
	"type":                             "Type",
	"ucsblade":                         "UcsBlade",
	"ucsblades":                        "UcsBlades",
	"ucsdn":                            "UcsDn",
	"ucsmanager":                       "UcsManager",
	"ucsmanagerid":                     "UcsManagerId",
	"ucsprofile":                       "UcsProfile",
	"ucsprofilefromblade":              "UcsProfileFromBlade",
	"ucsprofiletoblade":                "UcsProfileToBlade",
	"ucstemplate":                      "UcsTemplate",
	"ucstemplateandassocaciatetoblade": "UcsTemplateAndAssocaciateToblade",
	"unhealthythreshold":               "UnhealthyThreshold",
	"uploadpercentage":                 "UploadPercentage",
	"url":                              "Url",
	"usage":                            "Usage",
	"usageid":                          "UsageId",
	"usageinterface":                   "UsageInterface",
	"usagerecord":                      "UsageRecord",
	"usagetype":                        "UsageType",
	"usagetypeid":                      "UsageTypeId",
	"usehttps":                         "UseHttps",
	"user":                             "User",
	"userapikey":                       "UserApiKey",
	"userdata":                         "UserData",
	"userid":                           "UserId",
	"userkeys":                         "UserKeys",
	"username":                         "UserName",
	"userpublictemplateenabled":        "UserPublicTemplateEnabled",
	"usersecretkey":                    "UserSecretKey",
	"usersecuritygrouplist":            "UserSecurityGroupList",
	"value":                            "Value",
	"vcenter":                          "Vcenter",
	"vcsdeviceid":                      "VcsDeviceId",
	"version":                          "Version",
	"vgpu":                             "Vgpu",
	"virtualmachine":                   "VirtualMachine",
	"virtualmachinedisplayname":        "VirtualMachineDisplayName",
	"virtualmachineid":                 "VirtualMachineId",
	"virtualmachineids":                "VirtualMachineIds",
	"virtualmachinename":               "VirtualMachineName",
	"virtualsize":                      "VirtualSize",
	"virtualmachineuserdata":           "VirtualMachineUserData",
	"virtualrouterelement":             "VirtualRouterElement",
	"vlan":                             "Vlan",
	"vlanid":                           "VlanId",
	"vlaniprange":                      "VlanIpRange",
	"vlanname":                         "VlanName",
	"vlanrange":                        "VlanRange",
	"vmaffinitygroup":                  "VMAffinityGroup",
	"vmavailable":                      "VmAvailable",
	"vmdisplayname":                    "VmDisplayName",
	"vmgroupid":                        "VmGroupId",
	"vmguestip":                        "VmGuestIp",
	"vmidipmap":                        "VmIdIpmap",
	"vmipaddress":                      "VmIpAddress",
	"vmlimit":                          "VmLimit",
	"vmname":                           "VmName",
	"vmpassword":                       "VMPassword",
	"vmprofileid":                      "VmProfileId",
	"vmrunning":                        "VmRunning",
	"vmsnapshot":                       "VMSnapshot",
	"vmsnapshotid":                     "VMSnapshotId",
	"vmstate":                          "VmState",
	"vmstopped":                        "VmStopped",
	"vmtotal":                          "VmTotal",
	"vmwaredc":                         "VmwareDc",
	"vmwarenetworklabel":               "VmwareNetworkLabel",
	"vnsdeviceid":                      "VnsDeviceId",
	"volumeavailable":                  "VolumeAvailable",
	"volume":                           "Volume",
	"volumeid":                         "VolumeId",
	"volumelimit":                      "VolumeLimit",
	"volumeonfiler":                    "VolumeOnFiler",
	"volumesonfiler":                   "VolumesOnFiler",
	"volumename":                       "VolumeName",
	"volumetotal":                      "VolumeTotal",
	"volumetype":                       "VolumeType",
	"vpcavailable":                     "VpcAvailable",
	"vpc":                              "Vpc",
	"vpcid":                            "VpcId",
	"vpclimit":                         "VpcLimit",
	"vpcoffering":                      "VpcOffering",
	"vpcofferingid":                    "VpcOfferingId",
	"vpctotal":                         "VpcTotal",
	"vpnconnection":                    "VpnConnection",
	"vpncustomergateway":               "VpnCustomerGateway",
	"vpngateway":                       "VpnGateway",
	"vpnuser":                          "VpnUser",
	"vsmconfigmode":                    "VsmConfigMode",
	"vsmconfigstate":                   "VsmConfigState",
	"vsmctrlvlanid":                    "VsmCtrlVlanId",
	"vsmdeviceid":                      "VsmDeviceId",
	"vsmdevicename":                    "VsmDeviceName",
	"vsmdevicestate":                   "VsmDeviceState",
	"vsmdomainid":                      "VsmDomainId",
	"vsmipaddress":                     "VsmIpAddress",
	"vsmmgmtvlanid":                    "VsmMgmtVlanId",
	"vsmpassword":                      "VsmPassword",
	"vsmpktvlanid":                     "VsmPktVlanId",
	"vsmstoragevlanid":                 "VsmStorageVlanId",
	"vsmusername":                      "VsmUserName",
	"xennetworklabel":                  "XenNetworkLabel",
	"zone":                             "Zone",
	"zoneid":                           "ZoneId",
	"zonename":                         "ZoneName",
	"zonesnetworkspans":                "ZonesNetworkspans",
	"zonetoken":                        "Zonetoken",
}
